### ISSUE TITLE
[Recommendation] Redesign folder icons.

### ISSUE THREAD

**Issue by frostheart** [sixsixfive/Hedera#2]
It's not really an issue but a recommendation. I would recommend you to redesign folder icons, 'cause they are a little bit odd(in my point of view they are inconsistent with the whole theme and  a little bit "ugly").

And btw thank you for a great theme suit.

**Comment by sixsixfive** [comment]
yep thats already decided, however that takes a lot time since thats ~20 icons(folder, network folder, xdg-places, menu folders , different colors etc.) in 4 different sizes. I tought about something neutral like brown/ecru.

**Comment by gericom-hummer** [comment]
Another [Recommendation] 
I think the icon theme should be changed to Hedera as well and drop the old Ivy name. Thanks.

**Comment by sixsixfive** [comment]
that is already the case its called [Hedera](https://en.wikipedia.org/wiki/Hedera_helix) but like [breeze](https://github.com/KDE/breeze/blob/master/cursors/Breeze/Breeze/index.theme) that will be [translated](https://github.com/sixsixfive/Hedera/blob/master/Other/themes/Hedera/index.theme) depending on your locale

**Comment by frostheart** [comment]
I think ecru color should be fine. I like non distracting pale colors.

**Comment by sixsixfive** [comment]
how about one of those?

![unbenannt](https://cloud.githubusercontent.com/assets/3780774/21597526/5c459e82-d14c-11e6-89cb-b7dc53deb0e3.png)

**Comment by happydemic** [comment]
The ecru will go better with the violet highlight in the gtk theme than the blue does, I think. 

Some users might prefer to keep the blue folders as an option on the icon theme so as to match well with other gtk themes. Oranchelo, Ultra-Flat and some other icon themes offer a choice of folder colours, so perhaps Hedera could do that too (e.g. Hedera and Hedera-Blue).

**Comment by sixsixfive** [comment]
@happydemic 

thats something i wanted to do long time ago but it will be a bit different instead of creating another theme or a theme with blue folders that will inherit the main theme(qt does not fully support inherit) it will be possible to choose the folder color with the config script - however the old folder style will go away the new one will be available in all colors that the old one was(eg: https://github.com/sixsixfive/Hedera/blob/master/Other/icons/Hedera/48/folders/folder-orange.png just a bit brighter)

also another example:

![unbenannt](https://cloud.githubusercontent.com/assets/3780774/21643462/abbbe772-d288-11e6-855d-a233622ce1f2.png)

**Comment by frostheart** [comment]
As for me it's look like too gnomish (smooth, maybe they should be more sharper), but much more better than the original one.

**Comment by sixsixfive** [comment]
they are now included still not fully finished but usable. a different color can be chosen with the config script
